### ISSUE TITLE
Create a script for updating EoL XO laptops

### ISSUE THREAD

**Issue by jflory7** [FOSSRIT/toolbox#3]
In the last class of HFOSS today, we identified an issue that some XO laptops are having. Some of them, when flashed from stock, are using EoL repositories for Fedora 18. Because of that, it is impossible to update them or install other packages, like `git` or `pygame`.

A script could solve this problem by pulling down the correct repo files, the GPG key, importing it, and then updating the system. This shouldn't be too hard to do, and I will try to add it in soon.

CCing @ritjoe on this one.

**Comment by ritjoe** [comment]
I'm labelling this wontfix and closing it because it's a constraint we inherit from upstream: There is no OS support for the XO models we have based on anything newer than Fedora 18. Someday someone might hack something lighter but yet still being maintained, and that would be a great project should someone at RIT or elsewhere choose to embrace it, but it seems no one has the resources to do this now.

I go into some detail what our response to this challenge has recently been, in this comment in a PyCut activity upgrade issue: https://github.com/FOSSRIT/PyCut/pull/44#issuecomment-358959569
